In [21]:
from pathlib import Path

import sys

PROJECT_ROOT = Path.cwd().parent

sys.path.append(str(PROJECT_ROOT))

In [22]:
import src.utils.dataset_analyzer as analyzer

import src.features.extract_features as features

In [23]:
dataset = analyzer.load_dataset(
    PROJECT_ROOT/"data/raw/RML2016.10a_dict.pkl"
)

2026-07-01 16:27:58,417 | INFO | Loading dataset...
2026-07-01 16:28:03,527 | INFO | Dataset loaded successfully.

In [24]:
first_key = list(dataset.keys())[0]

signal = dataset[first_key][0]

In [25]:
features = features.extract_time_features(signal)

features

{'Mean': np.float32(0.0078124995),
 'Std': np.float32(0.0027395806),
 'Variance': np.float32(7.505302e-06),
 'Maximum': np.float32(0.016469846),
 'Minimum': np.float32(0.00040934916),
 'Median': np.float32(0.008003613),
 'RMS': np.float32(0.008278916),
 'PeakToPeak': np.float32(0.016060496),
 'Energy': np.float32(0.008773178),
 'MeanAbsolute': np.float32(0.0078124995),
 'AbsolutePeak': np.float32(0.016469846),
 'CrestFactor': np.float32(1.9893723),
 'ShapeFactor': np.float32(1.0597013),
 'ImpulseFactor': np.float32(2.1081405)}

In [26]:
import pandas as pd

df = pd.DataFrame([features])

df

,Mean,Std,Variance,Maximum,Minimum,Median,RMS,PeakToPeak,Energy,MeanAbsolute,AbsolutePeak,CrestFactor,ShapeFactor,ImpulseFactor
0,0.007812,0.00274,0.000008,0.01647,0.000409,0.008004,0.008279,0.01606,0.008773,0.007812,0.01647,1.989372,1.059701,2.10814

In [27]:
FEATURE_PATH = PROJECT_ROOT/"results"/"features"

FEATURE_PATH.mkdir(parents=True,exist_ok=True)

df.to_csv(
    FEATURE_PATH/"sample_features.csv",
    index=False
)

In [28]:
import importlib
import src.features.extract_features as feat

importlib.reload(feat)

In [29]:
features = feat.extract_features(signal)

pd.DataFrame([features])

,Mean,Std,Variance,Maximum,Minimum,Median,RMS,PeakToPeak,Energy,MeanAbsolute,...,SpectralSpread,SpectralEntropy,PSDMean,PSDMaximum,IMean,QMean,IStd,QStd,IQCorrelation,PhaseStd
0,0.007812,0.00274,0.000008,0.01647,0.000409,0.008004,0.008279,0.01606,0.008773,0.007812,...,48.102485,4.788886,0.000069,0.001079,-0.000475,0.000877,0.005524,0.006085,0.379323,1.77863

In [30]:
for i, feature in enumerate(features.keys(), 1):
    print(f"{i:02d}. {feature}")

01. Mean
02. Std
03. Variance
04. Maximum
05. Minimum
06. Median
07. RMS
08. PeakToPeak
09. Energy
10. MeanAbsolute
11. AbsolutePeak
12. CrestFactor
13. ShapeFactor
14. ImpulseFactor
15. FFTMean
16. FFTStd
17. FFTMaximum
18. FFTEnergy
19. DominantFrequency
20. SpectralCentroid
21. SpectralSpread
22. SpectralEntropy
23. PSDMean
24. PSDMaximum
25. IMean
26. QMean
27. IStd
28. QStd
29. IQCorrelation
30. PhaseStd